### ISSUE TITLE
Run fails with docker

### ISSUE THREAD

**Issue by o0larrylurex0o** [Patrowl/PatrowlDocs#13]
Hello, 
When trying to run the docker published on docker hub I keep getting this error several times during the boot

```
File "/opt/patrowl-manager/env/lib/python2.7/site-packages/psycopg2/__init__.py", line 130, in connect     
conn = _connect(dsn, connection_factory=connection_factory, **kwasync)      
django.db.utils.OperationalError: could not connect to server: Connection refused                                                                               
        Is the server running on host "localhost" (::1) and accepting           
        TCP/IP connections on port 5432?                                        
could not connect to server: Connection refused                                 
        Is the server running on host "localhost" (127.0.0.1) and accepting     
        TCP/IP connections on port 5432?
```  

but in the end I got

`[+] Start Supervisord (Celery workers)                                          
[+] Starting server                                                             
[2018-12-11 14:42:45 +0000] [54] [INFO] Starting gunicorn 19.9.0                
[2018-12-11 14:42:45 +0000] [54] [INFO] Listening at: http://0.0.0.0:8003 (54)  
[2018-12-11 14:42:45 +0000] [54] [INFO] Using worker: sync                      
[2018-12-11 14:42:45 +0000] [58] [INFO] Booting worker with pid: 58`

when trying to log to @IP:8003 I got a 500 error

As I understood the docker is still under developpement ? SO is this problem known or am I doign something wrong ?

Thx

**Comment by MaKyOtOx** [comment]
Hi !
The first message could reveal an issue for accessing the posgres DB :/
Could you please tell us the exact command used to deploy the PatrowlManager ? If you tried something like `docker run patrowl/patrowl-manager-community-edition:latest`, it will fail. Because this image includes only the Python application + Supervisord.

Go to the PatrowlManager folder and try `docker-compose up`.

Many thanks for your feedback :)
