### ISSUE TITLE
Docker show some errors

### ISSUE THREAD

**Issue by ST2Labs** [Patrowl/PatrowlDocs#3]
Hi, 

I'm working on dockerize your awesome apps !! Congrats!

[!] Here some errors when make migrations & migrate

![image](https://user-images.githubusercontent.com/9781565/42631469-a05459ee-85da-11e8-9e3a-dfc6ff2e5bec.png)

Best Regards

**Comment by MaKyOtOx** [comment]
Hi ! Thank you for your support.
The dockerization of the Engines is OK but PatrowlManager is not yet functional :/ The `Dockerfile` and the `docker-entrypoint.sh`files are just first tests. 
Because the Manager is more complex, we though **docker-compose** was a good idea (embedding rabbitmq, celery workers, postgresql db and the Django app) but we did not had the time to make it working yet. But we believe the full dockerization should be in the highest priorities.

**Comment by ST2Labs** [comment]
Hi,

I'm working on my own docker-compose.yml, and own Dockerfile to "run" PatrowlManager...

Now I have PatrolwManager working over docker image ... but I need test more ... because now I'm build some engine to eval & checks..

Thanks in advance ...

Great works !

**Comment by MaKyOtOx** [comment]
Thanks again ! We look forward for your next feedbacks and if possible a proposition of `docker-compose.yml` :)

**Comment by ainich** [comment]
nmap docker access - 0.0.0.0:15001 in readme :5001
