### ISSUE TITLE
nmap docker access - 0.0.0.0:15001 in readme :5001

### ISSUE THREAD

**Issue by MaKyOtOx** [Patrowl/PatrowlDocs#8]
_Originally posted by @ainich in https://github.com/Patrowl/PatrowlDocs/issues/3#issuecomment-431979416_

**Comment by MaKyOtOx** [comment]
Where do you see that @ainich ?

**Comment by LeoDub** [comment]
Hi MaKyOtOx,

The **issue** is in the file start-docker-engines.sh (in scripts of engines directory)

docker stop ${engine_dir##*/}-docker-001
    docker run -d --rm -p **1**$engine_port:$engine_port     # <== 1 before $engine_port var

So port is 15001 rather than 5001

Other issue is : 
iptables rules are not set for this port (5001), so it is not possible to get Ready status from th manager.

When all theses issues are fixed, I tried to start nmap on ip.
Error 500 happened inside nmap docker. 

11:14:58.415317 IP 172.17.0.1.58402 > 172.17.0.2.commplex-link: Flags [P.], seq 1:170, ack 1, win 229, options [nop,nop,TS val 2233555 ecr 2233554], length 169
E....]@.@............".......r......X......
."..."..GET /engines/nmap/status HTTP/1.1
Host: 192.168.56.11:15001
Connection: keep-alive
Accept-Encoding: gzip, deflate
Accept: */*
User-Agent: python-requests/2.18.1

................

11:14:58.418651 IP 172.17.0.2.commplex-link > 172.17.0.1.58402: Flags [P.], seq 1:166, ack 170, win 235, options [nop,nop,TS val 2233558 ecr 2233555], length 165
E.....@.@..............".r.....3....X......
."..."..HTTP/1.1 500 INTERNAL SERVER ERROR
Server: gunicorn/19.9.0
Date: Wed, 24 Oct 2018 15:14:58 GMT
Connection: close
Content-Type: text/html
Content-Length: 291

Hope this help!

**Comment by MaKyOtOx** [comment]
Hi,
Still blocked with the last update ?
Thks for feedbacks !!

**Comment by joaodomingos** [comment]
Having the same problem with dockers, I run nmap engine in a docker instance with the IP 172.17.0.2 so when I configure the new engine, the URL should be "http://172.17.0.2:5001/engines/nmap/" right?
